---

pagetitle: "2024 Biennial Transparency Report Projections Chapter: Tables & Figures"
output:
  html_document:

---

```{r setup}
source('packages.R')
library(targets)
library(tarchetypes)
tar_source()
tar_load(c(projections_all_sm, config))
```

```{r data}
net_ghg = projections_all_sm %>%
  group_by(proj_name, grouping, year) %>%
  summarise(sum = sum(sum)) %>%
  filter(year %in% config$fives)

ghgi = net_ghg %>% filter(proj_name == "ghgi")
proj_no_connect = net_ghg %>% 
  filter(proj_name != "ghgi")

connect = ghgi[ghgi$year == 2021,]$sum
baseline = ghgi[ghgi$year == 2005,]$sum

proj_connect = proj_no_connect %>% 
  group_by(proj_name) %>%
  slice(1) %>%
  mutate(
    year = 2021,
    sum = ghgi$sum[ghgi$year == 2021])

proj = rbind(proj_no_connect, proj_connect) %>%
  mutate(year = as.numeric(year))

targets = data.frame(
  year = c(2020, 2025, 2030),
  ymin = c((baseline * (1-.169)), (baseline * (1-.26)), (baseline * (1-.50))),
  ymax = c((baseline * (1-.171)), (baseline * (1-.28)), (baseline * (1-.52))),
  grouping = c("17% Below 2005","26-28% Below 2005","50-52% Below 2005")
)
```

```{r proj function}
projections = br_project(ghgi, proj, targets = TRUE)
projections
```
