---
title: "BTR Report"
output:
  html_document:
    toc: yes
    theme: spacelab
date: "`r Sys.time()`"
---

```{r,echo = FALSE, results = "show", warning = FALSE, message = FALSE, error = FALSE}
knitr::opts_chunk$set(echo = FALSE, results = "show", warning = FALSE, message = FALSE, error = FALSE, 
                      fig.align = "center", fig.width = 9, fig.height = 5)
```

```{r}
library(targets)
library(tarchetypes)
tar_source()
```

```{r}
tar_load(c(config,
           settings,
           data_long_clean,
           figmap_nrgco2_stackbar,
           figmap_nrgco2_timeseries,
           figmap_nrgco2_diffbar,
           figmap_draftbriefing_stackbar,
           projections_all_sm))
```

```{r}
source('packages.R')
source("scripts/theming.R")
```

# Tables

### Table 1: Historical and Projected U.S. GHG Emissions (2024 Policy Baseline), by Gas: 2005-2040 (MMTCO~2~e)
```{r create df}
gas_df <- create_summary_table('gas','wm', projections_all_sm, config)
sector_df <- create_summary_table('usproj_sector', 'wm', projections_all_sm, config)
```

```{r gas summary}
gas_table <- create_html_table(gas_df, 'Gas',config)
gas_table
```

### Table 2: Historical and Projected U.S. GHG Emissions (2024 Policy Baseline), by Sector: 2005-2040 (MMTCO~2~e)
```{r sector summary}
sector_table <- create_html_table(sector_df, 'Sector',config)
sector_table
```

# Figures


### Figure 1: U.S. Net GHG Emissions Projections
```{r data}
net_ghg = projections_all_sm %>%
  group_by(proj_name, grouping, year) %>%
  summarise(sum = sum(sum)) %>%
  filter(year %in% config$fives)

ghgi = net_ghg %>% filter(proj_name == "ghgi")
proj_no_connect = net_ghg %>% 
  filter(proj_name != "ghgi")

connect = ghgi[ghgi$year == 2022,]$sum
baseline = ghgi[ghgi$year == 2005,]$sum

proj_connect = proj_no_connect %>% 
  group_by(proj_name) %>%
  slice(1) %>%
  mutate(
    year = 2022,
    sum = ghgi$sum[ghgi$year == 2022])

proj = rbind(proj_no_connect, proj_connect) %>%
  mutate(year = as.numeric(year))

ndc_targets = data.frame(
  year = c(2020, 2025, 2030),
  ymin = c((baseline * (1-.169)), (baseline * (1-.26)), (baseline * (1-.50))),
  ymax = c((baseline * (1-.171)), (baseline * (1-.28)), (baseline * (1-.52))),
  grouping = c("17% Below 2005","26-28% Below 2005","50-52% Below 2005")
)
```

```{r proj function}
projections = br_project(ghgi, proj, config, targets = ndc_targets)
projections

```


```{r}

proj_all_sm_sb <- projections_all_sm %>%
  mutate(gas = case_when(gas %in% c("CO2") ~ "CO2",
                         !gas %in% c("CO2", 'LULUCF Sink') ~ "Non-CO2",
                         gas %in% c("LULUCF Sink") ~ "LULUCF Sink")) %>%
  group_by(proj_name,year,gas) %>%
  summarise(mmtco2e = sum(sum), .groups = 'drop') %>%
  filter(year >= config$base_year) %>%
  filter(year %in% config$base_proj)

no_ghgi <- proj_all_sm_sb %>% filter(!proj_name == 'ghgi')

ghgi <- proj_all_sm_sb %>% filter(proj_name == 'ghgi')

dfs <- list()

for(name in unique(no_ghgi$proj_name)) {
  df <- proj_all_sm_sb %>% filter(proj_name == name)
  add_ghgi <- ghgi %>%
    rbind(df) %>%
    mutate(proj_name = name)
  
  dfs[[name]] <- add_ghgi

}

proj_all_sm_sb_final <- bind_rows(dfs)

net_co2_df <- proj_all_sm_sb_final %>%
  group_by(proj_name, year) %>%
  summarise(net_co2 = sum(mmtco2e), .groups = 'drop')

proj_all_sm_sb_join <- proj_all_sm_sb_final %>%
  left_join(net_co2_df, by = c('proj_name','year')) %>%
  mutate(year = as.factor(year)) %>%
  mutate(gas = factor(gas, levels = c('CO2','Non-CO2','LULUCF Sink')))


fills <- c("CO2" =  "#0388B3",
           "Non-CO2" = "#E6544D",
           "LULUCF Sink" = "#16B231")
  

```

```{r}
proj_all_stackbar <- br_project_sb(proj_all_sm_sb_join, config, fills)
proj_all_stackbar

```

