---
pagetitle: "2024 Biennial Transparency Report Projections Chapter: Historical and Projected GHG Tables & Figures"
output:
  html_document:
    number_sections: false
    highlight: tango
    fontsize: 12
    fig_caption: false
    toc: yes
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    theme: spacelab
params:
  mode: "interactive"
---

```{r,echo = FALSE, results = "show", warning = FALSE, message = FALSE, error = FALSE}
knitr::opts_chunk$set(echo = FALSE, results = "show", warning = FALSE, message = FALSE, error = FALSE, fig.align = "center", fig.width = 9, fig.height = 7)


``` 

```{r}
source('packages.R')
library(targets)
library(tarchetypes)
tar_source()
```

```{r}

tar_load(
  c(
    config,
    settings,
    data_long_clean,
    projections_all_sm,
    total_gross_emissions,
    ghgi_comp_tab,
    projections_ghgi,
    past_proj
    )
  )

source("scripts/theming.R")

```

# BTR Tables and Figures: BRVS & BTR Sensitivities Comparison
## BTR Main Plot w/ LEEP Report Comparison {.tabset}


```{r}
net_ghg <- projections_ghgi %>%
  filter(year %in% config$fives50,
         !grouping == "wm_ltslulucf") %>% 
  group_by(proj_name,grouping,year) %>%
  summarise(value = sum(value)) %>%
  mutate(grouping = case_when(grouping == 'wm' ~ "2024 Policy Baseline",
                              grouping == 'wm_sens' ~ "2024 BTR, Sens.",
                              TRUE~grouping))

ghgi <- net_ghg %>%
  filter(grouping == 'ghgi')

net_ghg_ribbon <- net_ghg %>%
  group_by(grouping,year) %>%
  summarise(max = max(value),
            min = min(value))

connect_brvs <- net_ghg_ribbon %>%
  filter(year == 2022) %>%
  mutate(grouping = "IRA")
connect_wm <- net_ghg_ribbon %>%
  filter(year == 2022) %>%
  mutate(grouping = "2024 Policy Baseline")
connect_wm_sens <- net_ghg_ribbon %>%
  filter(year == 2022) %>%
  mutate(grouping = "2024 BTR, Sens.")

net_ghg_final <- net_ghg_ribbon %>%
  filter(!grouping == 'ghgi') %>% 
  rbind(connect_brvs,
        connect_wm,
        connect_wm_sens)

baseline = ghgi[ghgi$year == 2005,]$value

ndc_targets = data.frame(
  year = c(2020, 2025, 2030),
  ymin = c((baseline * (1-.169)), (baseline * (1-.26)), (baseline * (1-.50))),
  ymax = c((baseline * (1-.171)), (baseline * (1-.28)), (baseline * (1-.52))),
  grouping = c("17% Below 2005","26-28% Below 2005","50-52% Below 2005")
)


p <- ggplot() +
  geom_line(ghgi, mapping = aes(x = year, y = value), color = 'black') +
  geom_ribbon(data = net_ghg_final, aes(x = year, ymax = max, ymin = min, group = grouping, fill = grouping, color = grouping), alpha = .6) +
    # theming
    labs(title = "",
         y = expression(paste("Net GHG Emissions (MMt ", CO[2], "e)", sep = "")),
         x = "",
         color = "",
         fill = "") +
    scale_y_continuous(limits = c(0, 7200), expand = c(0, 0),
                       breaks = c(2000,4000,6000,round(ghgi$value[1])),
                       labels = comma) +
    scale_x_continuous(breaks = c(2005, 2010, 2015, 2020, 2022, 2025, 2030, 2035, 2040, 2045, 2050), expand = c(0,0)) +
  scale_subpalette_single(unique(net_ghg_final$grouping)) +
    guides(fill = guide_legend(nrow = 4, byrow = T)) +
    geom_hline(aes(yintercept = 0)) +
    theme_btr() +
    theme(
      legend.position = "inside",
      legend.position.inside = c(0.15, 0.2))


projections = p +
  geom_rect(
    data = ndc_targets %>%
      filter(year == 2020),
    aes(
      ymin = ymin,
      ymax = ymax,
      xmin = year - .3,
      xmax = year + .3,
      color = grouping,
      fill = grouping
    ),
    alpha = 0.5
  ) +
  geom_rect(
    data = ndc_targets %>% filter(year == 2025),
    aes(
      ymin = ymin,
      ymax = ymax,
      xmin = year - .3,
      xmax = year + .3,
      color = grouping,
      fill = grouping
    ),
    alpha = 0.5
  ) +
  geom_rect(
    data = ndc_targets %>% filter(year == 2030),
    aes(
      ymin = ymin,
      ymax = ymax,
      xmin = year - .3,
      xmax = year + .3,
      color = grouping,
      fill = grouping
    ),
    alpha = 0.5
  ) +
  geom_hline(
    data = (ndc_targets %>% filter(year == 2020)),
    aes(yintercept = ymax - .01),
    linetype = "dashed",
    color = "gray",
    size = 0.4,
    alpha = 0.5
  ) +
  geom_hline(
    data = (ndc_targets %>% filter(year != 2020)),
    aes(yintercept = ymax),
    linetype = "dashed",
    color = "gray",
    size = 0.4,
    alpha = 0.5
  ) +
  geom_hline(
    data = (ndc_targets %>% filter(year != 2020)),
    aes(yintercept = ymin),
    linetype = "dashed",
    color = "gray",
    size = 0.4,
    alpha = 0.5
  )

projections

```


```{r data}
net_ghg = projections_all_sm %>%
  group_by(proj_name, grouping, year) %>%
  summarise(sum = sum(sum)) %>%
  filter(year %in% config$fives)

ghgi = net_ghg %>% 
  filter(proj_name == "ghgi") %>% 
  mutate(grouping = "Historical")
proj_no_connect = net_ghg %>% 
  filter(proj_name != "ghgi")

connect = ghgi[ghgi$year == settings$base_year,]$sum
baseline = ghgi[ghgi$year == 2005,]$sum

proj_connect = proj_no_connect %>% 
  group_by(proj_name) %>%
  slice(1) %>%
  mutate(
    year = settings$base_year,
    sum = ghgi$sum[ghgi$year == settings$base_year])

proj = rbind(proj_no_connect, proj_connect) %>%
  mutate(year = as.numeric(year)) %>%
  filter(grouping %in% c("IRA", 'wm')) %>%
  mutate(grouping = case_when(
    grouping == "wm"~"2024 Policy Baseline",
    grouping == "IRA" ~ "LEEP",
    TRUE~grouping))

ndc_targets = data.frame(
  year = c(2020, 2025, 2030),
  ymin = c((baseline * (1-.169)), (baseline * (1-.26)), (baseline * (1-.50))),
  ymax = c((baseline * (1-.171)), (baseline * (1-.28)), (baseline * (1-.52))),
  grouping = c("17% Below 2005","26-28% Below 2005","50-52% Below 2005")
)
```

### Net GHG Emissions

```{r proj function}
projections_leep = br_project_brvs_sens(ghgi, proj, settings, targets = ndc_targets)
projections_leep
```

```{r}
filename <- paste0("btr_main_fig_leep_",Sys.Date(),".png")
ggsave(paste0('output/',settings$version,"/tables_figs/btr_main_figs/main_fig_leep/",filename), create.dir = TRUE, height = 6)
```

```{r}
net_ghg = projections_all_sm %>%
  group_by(proj_name, grouping, year) %>%
  summarise(sum = sum(sum),.groups = 'drop') %>%
  filter(year %in% config$fives) %>%
  mutate(pct_change_05 = round((sum/sum[year==2005]-1),2))

ghgi = net_ghg %>% 
  filter(proj_name == "ghgi") %>%
  mutate(grouping = "Historical")
proj_no_connect = net_ghg %>% 
  filter(proj_name != "ghgi")

connect = ghgi[ghgi$year == settings$base_year,]$pct_change_05
baseline = ghgi[ghgi$year == 2005,]$pct_change_05

proj_connect = proj_no_connect %>% 
  group_by(proj_name) %>%
  slice(1) %>%
  mutate(
    year = settings$base_year,
    pct_change_05 = ghgi$pct_change_05[ghgi$year == settings$base_year])

proj = rbind(proj_no_connect, proj_connect) %>%
  mutate(year = as.numeric(year)) %>%
  filter(grouping %in% c("IRA",'wm')) %>%
  mutate(grouping = case_when(
    grouping == "wm"~"2024 Policy Baseline",
    grouping == "IRA" ~ "LEEP",
    TRUE~grouping))

ndc_targets = data.frame(
  year = c(2020, 2025, 2030),
  ymin = c(-.17, -.28, -.52),
  ymax = c(-.17, -.26, -.5),
  grouping = c("17% Below 2005","26-28% Below 2005","50-52% Below 2005")
)
```

### Percent Change from 2005

```{r}
projections_pct_change = br_project_pct_change(ghgi, proj, targets = ndc_targets)
projections_pct_change
```

```{r}
filename <- paste0("btr_main_fig_pctchange05_",Sys.Date(),".png")
ggsave(paste0('output/',settings$version,"/tables_figs/btr_main_figs/main_fig_leep/",filename), create.dir = TRUE)
```


### Comp. to Sens./BRVS

```{r}
#br_project_brvs_sens(ghgi, proj,)
```



## BR5:VS Comparison

```{r}

############################
# Voluntary Supplement Data
############################

vs_df <- data_long_clean %>% 
  filter(scenario == 'leep_IRA',
         variable %in% c("Emissions / Energy",
                         "Energy / GDP",
                         "GDP / Capita",
                         "Population"),
         year %in% config$table50,
         year > 2022) %>%
  select(model,year,variable,value)

index_df <- kaya_comp_renamed %>%
  filter(year == 2015,
         br_version == '2024 BTR') %>%
  mutate(model = 'EPA-GHGI',
         variable = case_when(variable == "Energy/GDP" ~ "Energy / GDP",
                              variable == "Emissions/Energy" ~ "Emissions / Energy",
                              variable == "GDP/Capita" ~ "GDP / Capita",
                              TRUE~variable)) %>%
  select(names(vs_df)) %>%
  distinct()

vs_df_rbind <- vs_df %>%
  rbind(index_df)

calc_df <- vs_df_rbind %>%
  group_by(variable) %>%
  mutate(pct_change_15 = round((value/value[year==2015]-1),2)) %>% 
  #mutate(pct_change_15 = round(((value - value[year == 2015]) / value[year == 2015]),2)) %>%
  mutate(index_value = 1 + pct_change_15) %>%
  ungroup() %>%
  filter(!(model == 'USREP-ReEDS' & variable %in% c('Population','GDP / Capita')))

ribbon_vs_df <- calc_df %>%
  group_by(variable,year) %>%
  summarise(max = max(index_value),
         min = min(index_value)) %>%
  mutate(br_version = "2022 BR5:VS") %>% 
  select(br_version, everything())

############################
# BTR Data
###########################

btr_kaya <- kaya_data_range %>%
  # filter(year %in% config$table,
  #        year >= 2015) %>%
  mutate(variable = case_when(variable == "Energy/GDP" ~ "Energy / GDP",
                              variable == "Emissions/Energy" ~ "Emissions / Energy",
                              variable == "GDP/Capita" ~ "GDP / Capita",
                              TRUE~variable)) %>%
  select(names(ribbon_vs_df))

kaya_full <- btr_kaya %>% rbind(ribbon_vs_df)



var_palette <- unique(btr_kaya$variable)

ggplot() +
  geom_ribbon(
    data = kaya_full,
    mapping = aes(
      x = year,
      ymin = min,
      ymax = max,
      fill = variable,
      color = variable,
      linetype = br_version
    ),
    alpha = 0.4,
    size = .7
  ) +
  scale_linetype_manual(values = c("2022 BR5:VS" = "dotted", "2024 BTR" = "solid")) +
  scale_subpalette_single(var_palette) +
  labs(y = "Key Factor Index \n(2015 = 1.0)", title = "2024 BTR Inputs (solid) vs. 2022 BR5: Voluntary Supplement (dotted)") +
  scale_x_continuous(breaks = config$table50, expand = c(0, 0)) +
  geom_vline(
    xintercept = settings$base_year,
    linetype = 'dashed',
    color = "black",
    alpha = 0.5
  ) +
  theme_btr() +
  theme(
    legend.background = element_rect(color = NA),
    legend.position = 'bottom',
    panel.grid.minor.x = element_blank()
  ) +
  guides(color = guide_legend(override.aes = list(alpha = 1)))
```

## GDP-Breakout, BR5:VS Comparison

```{r}

var_list <- c('GDP|Consumption',
              'GDP|Imports',
              'GDP|Exports',
              'GDP|Government',
              'GDP|Investment',
              'Output|Industry|Value',
              'Output|Industry|Volume')

gdp_df <- data_long_clean %>%
  filter(scenario %in% c('leep_IRA','wm'),
         variable %in% var_list,
         year %in% config$fives_proj,
         model %in% c('USREP-ReEDS', "OP-NEMS")) %>%
  select(model,scenario,year,variable,value) %>%
  group_by(scenario,year,variable) %>% 
  summarise(max = max(value),
            min = min(value))

var_palette <- unique(gdp_df$scenario)

ggplot(data = gdp_df) +
  geom_ribbon(aes(x = year, ymax = max, ymin = min, fill = scenario, color = scenario), alpha = .6) +
  facet_wrap(~variable, scales = 'free_y') +
  #scale_y_continuous(labels = scales::label_currency()) +
  scale_subpalette_single(var_palette) +
  theme_btr()

```


# Sector Analysis {.tabset}

```{r}
sector_vars <- c("Emissions|CO2|Energy|Demand|Buildings|Total",
                 "Emissions|CO2|Energy|Demand|Transportation|Total",
                 "Emissions|CO2|Energy|Demand|Industry and Fuel Production|Total",
                 "Emissions|CO2|Energy|Supply|Electricity")

lts_vars <- c("Emissions|CO2|Energy|Demand|Buildings|TotalDI",
              "Emissions|CO2|Energy|Demand|Transportation|TotalDI",
              "Emissions|CO2|Energy|Demand|Industry|TotalDI",
              "Emissions|CO2|Energy|Supply|Electricity")

# ghgi 24 data
ghgi_df <- ghgi_comp_tab %>%
  filter(model == config$model_hist) %>%
  filter(year %in% config$hist) %>%
  filter(variable %in% c(sector_vars,"Emissions|CO2|Energy|Demand|Industry|Total")) %>%
   mutate(variable = case_when(
     variable == "Emissions|CO2|Energy|Demand|Industry|Total" ~ "Emissions|CO2|Energy|Demand|Industry and Fuel Production|Total",
     TRUE~variable
   ))
# TODO: need to pull fuel production emissions from GHGI and create a new variable so that it can be included here for historical emissions

# LTS models and variables used for sector figures
lts_df <- data_long_clean %>%
  filter(model %in% config$model_lts) %>%
  filter(year %in% config$fives_proj_sm) %>%
  filter(variable %in% lts_vars) %>%
  # change names to match template update variable names
  mutate(variable = case_when(
    str_detect(variable, "Buildings") ~ "Emissions|CO2|Energy|Demand|Buildings|Total",
    str_detect(variable, "Transportation") ~ "Emissions|CO2|Energy|Demand|Transportation|Total",
    str_detect(variable, "Industry") ~ "Emissions|CO2|Energy|Demand|Industry and Fuel Production|Total",
    TRUE~variable))

# models used in the projections and variables used for sector figures
proj_models <- config$model_wm

proj_scens <- c('leep_IRA',
                'wm',
                'wm_highfuelcost',
                'wm_lowcostre',
                'wm_lowcostre_highfuelcost',
                'wm_adv',
                'wm_highogs',
                'wm_lowogs',
                'wm_adv',
                'wm_adv_max'
                )

sens_scens <- c('wm_highfuelcost',
                'wm_lowcostre',
                'wm_lowcostre_highfuelcost',
                'wm_adv',
                'wm_highogs',
                'wm_lowogs',
                'wm_adv',
                'wm_adv_max')

proj_df <- data_long_clean %>%
  filter(model %in% proj_models,
         year %in% config$fives_proj_sm,
         scenario %in% proj_scens,
         variable %in% sector_vars,
         region == 'United States') %>%
  mutate(grouping = case_when(scenario %in% sens_scens ~ "2024 BTR, Sens.",
                              scenario == 'wm' ~ '2024 Policy Baseline',
                              scenario == 'leep_IRA' ~ "2023 BR:VS"))

# 2030 and 2035 projections medians
median_df <- proj_df %>%
  group_by(year,variable) %>%
  summarise(value = median(value)) %>%
  mutate(model = "median",
         scenario = "wm",
         unit = "Mt CO2/yr",
         datasrc = "median calc",
         region = "United States") %>%
  select(names(proj_df))

# merge three datasets together
sector_df <- rbind(ghgi_df, lts_df, proj_df, median_df) %>%
  mutate(type = case_when(
    str_detect(model, "LTS") ~ "LTS",
    model %in% proj_models ~ "proj",
    model == "EPA-GHGI" ~ "GHGI",
    model == "median" ~ "median",
    TRUE~model)) 
```

```{r}
# buildings
buildings <- br_sectors(sector_df,
                       "Emissions|CO2|Energy|Demand|Buildings|Total",
                       expression(paste("Buildings Emissions (MMt C", O[2], ")")))

# electricity
electricity <- br_sectors(sector_df,
                       "Emissions|CO2|Energy|Supply|Electricity",
                       expression(paste("Electricity Emissions (MMt C", O[2], ")")))

# transportation
transportation <- br_sectors(sector_df,
                       "Emissions|CO2|Energy|Demand|Transportation|Total",
                       expression(paste("Transportation Emissions (MMt C", O[2], ")")))

# industry
industry <- br_sectors(sector_df,
                       "Emissions|CO2|Energy|Demand|Industry and Fuel Production|Total",
                       expression(paste("Industry Emissions (MMt C", O[2], ")")))
```


