---
title: "BTR Results Overview W/ Sensitivities"
output:
  html_document:
    toc: yes
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    theme: spacelab
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r,echo = FALSE, results = "show", warning = FALSE, message = FALSE, error = FALSE}
knitr::opts_chunk$set(echo = FALSE, results = "show", warning = FALSE, message = FALSE, error = FALSE, 
                      fig.align = "center", fig.width = 9, fig.height = 5)
```

```{r}
library(targets)
library(tarchetypes)
tar_source()
source('packages.R')
```

```{r}
tar_load(
  c(
    config,
    settings,
    data_long_clean,
    projections_all_sm, 
    figmap_deck_timeseries
    )
  )

source("scripts/theming.R")

saveit = function(title, settings, width = 10, height = 5) {
  ggsave(filename = paste0("output/",settings$version,"/results_overview_sens_deck/",title,".png"),
         
         create.dir = TRUE,
         width = width,
         height = height,
         units = "in")
}

bottom = theme(legend.position="bottom",legend.direction="vertical")
data_long_clean_100 = data_long_clean %>% mutate(value = value*100)
```

# Emissions {.tabset}

## Gross Emissions
```{r}
title = "Energy Emissions by Sector"
print_graph_for_save("time_series", config, data_long_clean, figmap_deck_timeseries, 9.1, "United States",
            level_var = c("Buildings", "Industry", "Transportation", "Electricity", "Petroleum Refining", "Total Energy")) +
  labs(title = "", y = expression(paste("Energy Emissions (Mt C", O[2],")"))) 
saveit(title,settings, width = 13)
```

## CCS
```{r}
title = "Carbon Capture and Storage (CCS)"
print_graph_for_save("time_series", config, data_long_clean, figmap_deck_timeseries, 39, "United States") +
  labs(title="", y = expression(paste("Captured and Stored Emissions (Mt C", O[2],")"))) +
  bottom
saveit(title,settings, width = 6)
```

# Primary/Final Energy {.tabset}

## Primary Energy 
```{r}
fossil = print_graph_for_save("time_series", config, data_long_clean, figmap_deck_timeseries, 6, "United States") +
  labs(title = "Fossil", y = "Primary Energy (EJ/yr)")

# Check GCAM nuclear units
non_fossil = print_graph_for_save("time_series", config, data_long_clean, figmap_deck_timeseries, 7, "United States") +
  labs(title = "Non-Fossil", y = "")

title = "Primary Energy"
fossil+non_fossil+plot_layout(guides = "collect", widths = c(1, 2))
saveit(title,settings, width = 15, height = 4)
```

## Final Energy {.tabset}

### Fuel
```{r}
title = "Final Energy by Source"
print_graph_for_save("time_series", config, data_long_clean, figmap_deck_timeseries, 1, "United States") +
  labs(title = "", y = "Final Energy (EJ/yr)") 
saveit(title,settings, width = 14)
```

### Percent Electricity
```{r}
title = "Energy Demand Met by Electricity"
print_graph_for_save("time_series", config, data_long_clean, figmap_deck_timeseries, 14, "United States",
                                  level_var = c("Buildings", "Industry", "Transportation","Total Electricity")) +
  scale_y_continuous(labels = percent_format()) +
  theme(axis.title.y = element_blank()) +
  labs(title = title) +
  bottom
saveit(title,settings, width = 6)
```

### Hydrogen
```{r}
title = "Hydrogen Demand"
print_graph_for_save("time_series", config, data_long_clean, figmap_deck_timeseries, 1.1, "United States") +
  labs(title = "", y = "Demand (EJ/yr)") +
  bottom
saveit(title,settings, width = 4)
```

# Electricity

## Load Growth
```{r}
title = "Load Growth"
print_graph_for_save("time_series", config, data_long_clean, figmap_deck_timeseries, 15.1, "United States") +
  labs(title = "") +
  bottom
saveit(title,settings,width=4)
```

## Generation by Source
```{r}
title = "Generation"
print_graph_for_save("time_series", config, data_long_clean, figmap_deck_timeseries, 15, "United States",
                         level_var = c("Coal", "Gas", "Oil","Solar", "Wind", "Total Generation")) +
  labs(title = "", y = "Electricity Generation (EJ/yr)")
saveit(title,settings,width=15)
```

## Capacity by Source
```{r}
title = "Capacity"
print_graph_for_save("time_series", config, data_long_clean, figmap_deck_timeseries, 16, "United States",
                         level_var = c("Coal", "Gas", "Oil","Solar", "Wind", "Storage", "Total Capacity")) +
  labs(title = "", y = "Electricity Capacity (GW)")
saveit(title,settings,width=15)
```

# Sectoral Energy Demand {.tabset}

## Buildings
```{r}
title = "Buildings Demand"
print_graph_for_save("time_series", config, data_long_clean, figmap_deck_timeseries, 17, "United States",
                                level_var = c("Coal", "Gas", "Oil", 'Electricity',"Total Energy")) +
  labs(title = "", y = "Buildings Demand (EJ/yr)") +
  bottom
saveit(title,settings,width=6)
```

## Industry
```{r}
title = "Industry Demand"
print_graph_for_save("time_series", config, data_long_clean, figmap_deck_timeseries, 18, "United States",
                                level_var = c("Coal", "Gas", "Oil", 'Electricity',"Total Energy")) +
  labs(title = "", y = "Industry Demand (EJ/yr)") +
  bottom
saveit(title,settings,width=6)
```

## Transportation {.tabset}

### Energy Demand
```{r}
title = "Transportation Demand"
print_graph_for_save("time_series", config, data_long_clean_100, figmap_deck_timeseries, 19, "United States") +
  labs(title = "", y = "Transportation Demand (EJ/yr)") +
  bottom
saveit(title,settings,width=6)
```

### Vehicle Sales and Stock

```{r}
print_graph_for_save("time_series", config, data_long_clean_100, figmap_deck_timeseries, 34, "United States")

print_graph_for_save("time_series", config, data_long_clean_100, figmap_deck_timeseries, 34, "United States")
```








