---
title: "BTR Results Overview"
output: html_document
date: "`r Sys.time()`"
---

```{r,echo = FALSE, results = "show", warning = FALSE, message = FALSE, error = FALSE}
knitr::opts_chunk$set(echo = FALSE, results = "show", warning = FALSE, message = FALSE, error = FALSE, 
                      fig.align = "center", fig.width = 9, fig.height = 5)
```


```{r}
library(targets)
library(tarchetypes)
tar_source()
```

```{r}
tar_load(config)
tar_load(settings)
tar_load(data_long_clean)
tar_load(figmap_btr_stackbar)
tar_load(figmap_btr_timeseries)
tar_load(figmap_btr_diffbar)
```

```{r}
source('packages.R')
source("scripts/theming.R")
```

# Emissions

## Energy CO2 Emissions Accounting {.tabset}

### Sector

```{r}
sector = print_graph("stacked_bar", config, data_long_clean, figmap_btr_stackbar, 18, "United States", scenario_rename = TRUE)
sector
```

### Model

```{r}
model = print_graph("time_series", config, data_long_clean, figmap_btr_timeseries, 9, "United States", scenario_rename = TRUE,
            level_var = c("Buildings", "Industry", "Transportation", "Supply", "Total Energy"))
model
```

