---
pagetitle: "TGE breakouts"
output:
  html_document:
    number_sections: false
    highlight: tango
    fontsize: 12
    fig_caption: false
    toc: yes
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    theme: spacelab
params:
  mode: "interactive"
---

```{r,echo = FALSE, results = "show", warning = FALSE, message = FALSE, error = FALSE}
knitr::opts_chunk$set(echo = FALSE, results = "show", warning = FALSE, message = FALSE, error = FALSE, fig.align = "center", fig.width = 9, fig.height = 7)


``` 


```{r}
source('packages.R')
library(targets)
library(tarchetypes)
tar_source()
```

```{r}

tar_load(
  c(
    config,
    settings,
    data_long_clean,
    projections_all_sm,
    projections_ghgi
    )
  )

source("scripts/theming.R")

```

# Gas and Sector Breakouts

## Main Grid

```{r}
nonco2 = projections_all_sm %>% 
  filter(grouping == "wm") %>%
  filter(usproj_sector != "LULUCF Sink") %>%
  filter(!(str_detect(proj_name, "usrr") & usproj_sector %in% c("Transportation","Energy") & year %in% c(2045, 2050))) %>%
  filter(!(usproj_sector == "Energy" & !year %in% c(2020, 2025, 2030, 2035, 2040, 2045, 2050))) %>%
  filter(year <= 2040)

ggplot() +
  geom_line(data = nonco2, aes(x=year,y=sum,group=proj_name,color=gas), linewidth = 1) +
  facet_grid(usproj_sector~gas, scales = "free_y") +
  labs(y = "Mt CO2e") +
  theme_btr() +
  theme(
    #text = element_text(size = 20),
        strip.text.x = element_text(size = 14),
        strip.text.y = element_text(size = 14),
        text = element_text(size = 14)) +
  nolegend
```

```{r}
ggsave(filename = paste0('output/',settings$version,"/tables_figs/tge_breakouts/main_fig.png"),width = 9, height = 7)

```


## Agriculture {.tabset}

### Main

```{r}

fig <- tge_breakout_figure(projections_ghgi, sector_select = 'Agriculture')
fig

```

### CH4

```{r}
fig <- tge_breakout_figure(projections_ghgi, sector_select = 'Agriculture', gas_select = 'CH4')

fig
```

### CO2

```{r}
fig <- tge_breakout_figure(projections_ghgi, sector_select = 'Agriculture', gas_select = 'CO2')

fig
```

### N2O

```{r}
fig <- tge_breakout_figure(projections_ghgi, sector_select = 'Agriculture', gas_select = 'N2O')

fig
```


## Energy {.tabset}

### Main

```{r}

fig <- tge_breakout_figure(projections_ghgi, sector_select = 'Energy')
fig

```

### CH4

```{r}
fig <- tge_breakout_figure(projections_ghgi, sector_select = 'Energy', gas_select = 'CH4')

fig
```

### CO2

```{r}
fig <- tge_breakout_figure(projections_ghgi, sector_select = 'Energy', gas_select = 'CO2')

fig
```

### N2O

```{r}
fig <- tge_breakout_figure(projections_ghgi, sector_select = 'Energy', gas_select = 'N2O')

fig
```


## Industrial Processes {.tabset}

### Main

```{r}

fig <- tge_breakout_figure(projections_ghgi, sector_select = 'IPPU')
fig

```

### CH4

```{r}
fig <- tge_breakout_figure(projections_ghgi, sector_select = 'IPPU', gas_select = 'CH4')

fig
```

### CO2

```{r}
fig <- tge_breakout_figure(projections_ghgi, sector_select = 'IPPU', gas_select = 'CO2')

fig
```

### HFCs

```{r}
fig <- tge_breakout_figure(projections_ghgi, sector_select = 'IPPU', gas_select = 'HFCs')

fig
```

### N2O

```{r}
fig <- tge_breakout_figure(projections_ghgi, sector_select = 'IPPU', gas_select = 'N2O')

fig
```

### NF3

```{r}
fig <- tge_breakout_figure(projections_ghgi, sector_select = 'IPPU', gas_select = 'NF3')

fig
```

### PFCs

```{r}
fig <- tge_breakout_figure(projections_ghgi, sector_select = 'IPPU', gas_select = 'PFCs')

fig
```


### SF6

```{r}
fig <- tge_breakout_figure(projections_ghgi, sector_select = 'IPPU', gas_select = 'SF6')

fig
```

## Transportation {.tabset}

### Main

```{r}

fig <- tge_breakout_figure(projections_ghgi, sector_select = 'Transportation')
fig

```

### CH4

```{r}
fig <- tge_breakout_figure(projections_ghgi, sector_select = 'Transportation', gas_select = 'CH4')

fig
```

### CO2

```{r}
fig <- tge_breakout_figure(projections_ghgi, sector_select = 'Transportation', gas_select = 'CO2')

fig
```

### N2O

```{r}
fig <- tge_breakout_figure(projections_ghgi, sector_select = 'Transportation', gas_select = 'N2O')

fig
```

## Waste {.tabset}

### Main

```{r}

fig <- tge_breakout_figure(projections_ghgi, sector_select = 'Waste')
fig

```

### CH4

```{r}
fig <- tge_breakout_figure(projections_ghgi, sector_select = 'Waste', gas_select = 'CH4')

fig
```


### N2O

```{r}
fig <- tge_breakout_figure(projections_ghgi, sector_select = 'Waste', gas_select = 'N2O')

fig

```


# Ad-hoc

```{r}
df <- projections_all_sm %>%
  filter(grouping == 'wm',
         gas == 'CO2',
         usproj_sector %in% c('Transportation','Energy'),
         year %in% config$table) %>%
  group_by(year,gas,usproj_sector) %>%
  summarise(max = max(sum),
            min = min(sum))

fig <- ggplot() +
  geom_ribbon(df, mapping = aes(x = year, ymin = min, ymax = max), fill = 'blue', color = 'blue', alpha = .7) +
  #geom_line(data = df, aes(x=year,y=sum,group=proj_name,color=gas), linewidth = 1) +
  facet_grid(usproj_sector~gas, scales = "free_y") +
   scale_x_continuous(breaks = c(2005, 2010, 2015, 2020, 2022, 2025, 2030, 2035, 2040, 2045, 2050), expand = c(0,0)) +
  labs(y = "Mt CO2e") +
  scale_y_continuous(labels = scales::comma) +
  theme_btr() +
  nolegend

fig

ggsave(paste0('output/',settings$version,"/tables_figs/tge_breakouts/co2_facet.png"), width = 5, create.dir = TRUE)

```


